# Generated by Django 2.2.12 on 2020-08-30 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('post_img', models.ImageField(default='', null=True, upload_to='profile/img')),
                ('post_video', models.FileField(default='', null=True, upload_to='profile/video')),
                ('status', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('birthdate', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default='')),
                ('profile_image', models.ImageField(default='', upload_to='profile/img')),
                ('friends', models.ManyToManyField(blank=True, to='Home.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment_id', models.IntegerField(default=1)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Post')),
                ('reply_of_comnt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.PostComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='id_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Profile'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='Home.Profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='Home.Profile')),
            ],
        ),
    ]
