# Generated by Django 2.2.12 on 2020-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200902_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile/img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='profile/video'),
        ),
    ]
